# Site Settings
title: Web Developer Website
description: "This website is created to showcase my work as a web developer and as a blog platform"
tagline: "Every developer needs a website"
baseurl: "/jekyll-review-october-2018"
url: http://mywebsite.com
excerpt_separator: <!-- more -->

timezone: 'Asia/Riyadh'

# Build Settings
markdown: kramdown
kramdown:
  input: GFM
  highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: false

# Sass
sass:
  sass_dir: _sass
  style: compressed

# Files to Exclude from Build
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - README.md

paginate: 2
paginate_path: '/blog/page:num/'
permalink: /blog/:title

autoprefixer:
  browsers:
  - last 2 versions

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-seo-tag
  - jemoji
  - jekyll-avatar
  - jekyll-autoprefixer

# Collections
collections_dir: my_collections
collections:
  projects:
    output: true
  dog_daycare:
    output: true
    permalink: /project/dog-daycare/:name
  developer_portfolio:
    output: true
    permalink: /project/developer-portfolio/:name

# Front Matter Defaults
defaults:
  - 
    scope:
      path: ""
      type: "projects"
    values:
      layout: "project"
  - 
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  -
    scope:
      path: "assets/img"
    values:
      image: true