# Site Settings
title: Web Developer Website
description: "This website is created to showcase my work as a web developer and as a blog platform"
tagline: "Every developer needs a website"
baseurl: ""
url: http://mywebsite.com

# Build Settings
markdown: kramdown
exclude: ["README.md"]

paginate: 2
paginate_path: '/blog/page:num/'

plugins: [jekyll-paginate]